"""Public exchange declarations and bundled exchange field groups."""

from vercor.exchange import Exchange, RegridderFactory
from vercor.fields import ExchangeField
from vercor.setups.exchange_recipes import (
    ATMOSPHERE_TO_DATA_OCEAN_FIELDS,
    ATMOSPHERE_TO_JCM_LAND_FLUX_FIELDS,
    ATMOSPHERE_TO_LAND_BASIC_FIELDS,
    ATMOSPHERE_TO_LAND_RADIATION_FIELDS,
    ATMOSPHERE_TO_LAND_STATE_FIELDS,
    ATMOSPHERE_TO_OCEAN_RADIATION_FIELDS,
    ATMOSPHERE_TO_OCEAN_STATE_FIELDS,
    ATMOSPHERE_TO_VEROS_FORCING_FIELDS,
    JCM_LAND_TO_ATMOSPHERE_FIELDS,
    LAND_TO_ATMOSPHERE_SOIL_FIELDS,
    LAND_TO_ATMOSPHERE_SURFACE_FIELDS,
    OCEAN_TO_ATMOSPHERE_SURFACE_FIELDS,
    OCEAN_TO_SEAICE_SURFACE_FIELDS,
    SEAICE_TO_OCEAN_FIELDS,
    SLAB_ATMOSPHERE_TO_LAND_FLUX_FIELDS,
    SLAB_ATMOSPHERE_TO_OCEAN_FIELDS,
    SLAB_ATMOSPHERE_TO_OCEAN_FLUX_FIELDS,
)

__all__ = [
    "ATMOSPHERE_TO_DATA_OCEAN_FIELDS",
    "ATMOSPHERE_TO_JCM_LAND_FLUX_FIELDS",
    "ATMOSPHERE_TO_LAND_BASIC_FIELDS",
    "ATMOSPHERE_TO_LAND_RADIATION_FIELDS",
    "ATMOSPHERE_TO_LAND_STATE_FIELDS",
    "ATMOSPHERE_TO_OCEAN_RADIATION_FIELDS",
    "ATMOSPHERE_TO_OCEAN_STATE_FIELDS",
    "ATMOSPHERE_TO_VEROS_FORCING_FIELDS",
    "Exchange",
    "ExchangeField",
    "JCM_LAND_TO_ATMOSPHERE_FIELDS",
    "LAND_TO_ATMOSPHERE_SOIL_FIELDS",
    "LAND_TO_ATMOSPHERE_SURFACE_FIELDS",
    "OCEAN_TO_ATMOSPHERE_SURFACE_FIELDS",
    "OCEAN_TO_SEAICE_SURFACE_FIELDS",
    "RegridderFactory",
    "SEAICE_TO_OCEAN_FIELDS",
    "SLAB_ATMOSPHERE_TO_LAND_FLUX_FIELDS",
    "SLAB_ATMOSPHERE_TO_OCEAN_FIELDS",
    "SLAB_ATMOSPHERE_TO_OCEAN_FLUX_FIELDS",
]
